title: sebanalysis
email: sebanalysis@protonmail.com
description: >-
  A place to learn about the taxonomy of things.
baseurl: "testsite"
url: ""
twitter_username: sebanalysis
github_username: sebanalysis
markdown: kramdown
remote_theme: time-machine
plugins:
  - jekyll-feed
