# customise this for yourself
title: sebanalysis
email: sebanalysis@protonmail.com
description: A place to learn about the taxonomy of things.
twitter_username: sebanalysis
github_username: sebanalysis
  
# delete if this is your only site on github pages
baseurl: "testsite"

# config
theme: jekyll-theme-minimal
repository: sebanalysis/testsite


