title: sebanalysis
email: sebanalysis@protonmail.com
description: >-
  A place to learn about the taxonomy of things.
baseurl: "testsite"
url: ""
twitter_username: sebanalysis
github_username: sebanalysis
markdown: kramdown
remote_theme: pages-themes/time-machine@v0.2.0
plugins:
  - jekyll-feed
  - jekyll-include-cache

